In [2]:
import numpy as np
import networkx as nx

# Crear el grafo
G = nx.Graph()

G.add_edge(0, 1, resistance=1.0)
G.add_edge(0, 2, resistance=2.0)
G.add_edge(1, 2, resistance=1.0)

# Convertir resistencias a conductancias
for u, v in G.edges():
    G[u][v]['weight'] = 1 / G[u][v]['resistance']

# Matriz laplaciana completa
L = nx.laplacian_matrix(G, weight='weight').toarray()

print("Matriz laplaciana completa:")
print(L)

# Fijar nodo de referencia V0 = 0
# Eliminamos fila y columna 0
L_reducida = L[1:, 1:]

print("\nMatriz laplaciana reducida:")
print(L_reducida)

# Definir corrientes (ejemplo)
I = np.array([1.0, -1.0])  # I1 = 1, I2 = 0

# Resolver sistema
V = np.linalg.solve(L_reducida, I)

print("\nVoltajes (V1, V2):")
print(V)

Matriz laplaciana completa:
[[ 1.5 -1.  -0.5]
 [-1.   2.  -1. ]
 [-0.5 -1.   1.5]]

Matriz laplaciana reducida:
[[ 2.  -1. ]
 [-1.   1.5]]

Voltajes (V1, V2):
[ 0.25 -0.5 ]


In [4]:
# Opcion 2 sin usar paquetes de grafos
import numpy as np

# Número de nodos
n = 3

# Matriz del sistema (Laplaciano)
L = np.zeros((n, n))

# Lista de resistencias: (nodo_i, nodo_j, R)
resistencias = [
    (0, 1, 1.0),
    (0, 2, 2.0),
    (1, 2, 1.0)
]

# Construcción de la matriz
for i, j, R in resistencias:
    G = 1.0 / R  # conductancia

    L[i, i] += G
    L[j, j] += G
    L[i, j] -= G
    L[j, i] -= G

print("Matriz L:")
print(L)

# Corrientes externas
I = np.array([0.0, 1.0, -1.0])

# Fijamos nodo 0 como tierra → eliminamos fila y columna
L_reducida = L[1:, 1:]
I_reducida = I[1:]

# Resolver sistema
V_reducido = np.linalg.solve(L_reducida, I_reducida)

# Reconstruir vector completo
V = np.zeros(n)
V[1:] = V_reducido

print("\nPotenciales en los nodos:")
for i in range(n):
    print(f"V_{i} = {V[i]:.4f}")

Matriz L:
[[ 1.5 -1.  -0.5]
 [-1.   2.  -1. ]
 [-0.5 -1.   1.5]]

Potenciales en los nodos:
V_0 = 0.0000
V_1 = 0.2500
V_2 = -0.5000
